// Code generated by protoc-gen-go.
// source: bfdatafeed.proto
// DO NOT EDIT!

/*
Package bfdatafeed is a generated protocol buffer package.

It is generated from these files:
	bfdatafeed.proto

It has these top-level messages:
	BfBarData
	BfGetTickReq
	BfGetBarReq
	BfDeleteTickReq
	BfDeleteBarReq
	BfDeleteContractReq
*/
package bfdatafeed

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import bfgateway "github.com/sunwangme/bfgo/api/bfgateway"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Bar周期类型，和文华财经保持一致
type BfBarPeriod int32

const (
	BfBarPeriod_PERIOD_UNKNOWN BfBarPeriod = 0
	BfBarPeriod_PERIOD_S01     BfBarPeriod = 1
	BfBarPeriod_PERIOD_S03     BfBarPeriod = 2
	BfBarPeriod_PERIOD_S05     BfBarPeriod = 3
	BfBarPeriod_PERIOD_S10     BfBarPeriod = 4
	BfBarPeriod_PERIOD_S15     BfBarPeriod = 5
	BfBarPeriod_PERIOD_S30     BfBarPeriod = 6
	BfBarPeriod_PERIOD_M01     BfBarPeriod = 7
	BfBarPeriod_PERIOD_M03     BfBarPeriod = 8
	BfBarPeriod_PERIOD_M05     BfBarPeriod = 9
	BfBarPeriod_PERIOD_M10     BfBarPeriod = 10
	BfBarPeriod_PERIOD_M15     BfBarPeriod = 11
	BfBarPeriod_PERIOD_M30     BfBarPeriod = 12
	BfBarPeriod_PERIOD_H01     BfBarPeriod = 13
	BfBarPeriod_PERIOD_H02     BfBarPeriod = 14
	BfBarPeriod_PERIOD_H03     BfBarPeriod = 15
	BfBarPeriod_PERIOD_H04     BfBarPeriod = 16
	BfBarPeriod_PERIOD_D01     BfBarPeriod = 17
	BfBarPeriod_PERIOD_W01     BfBarPeriod = 18
	BfBarPeriod_PERIOD_X01     BfBarPeriod = 19
)

var BfBarPeriod_name = map[int32]string{
	0:  "PERIOD_UNKNOWN",
	1:  "PERIOD_S01",
	2:  "PERIOD_S03",
	3:  "PERIOD_S05",
	4:  "PERIOD_S10",
	5:  "PERIOD_S15",
	6:  "PERIOD_S30",
	7:  "PERIOD_M01",
	8:  "PERIOD_M03",
	9:  "PERIOD_M05",
	10: "PERIOD_M10",
	11: "PERIOD_M15",
	12: "PERIOD_M30",
	13: "PERIOD_H01",
	14: "PERIOD_H02",
	15: "PERIOD_H03",
	16: "PERIOD_H04",
	17: "PERIOD_D01",
	18: "PERIOD_W01",
	19: "PERIOD_X01",
}
var BfBarPeriod_value = map[string]int32{
	"PERIOD_UNKNOWN": 0,
	"PERIOD_S01":     1,
	"PERIOD_S03":     2,
	"PERIOD_S05":     3,
	"PERIOD_S10":     4,
	"PERIOD_S15":     5,
	"PERIOD_S30":     6,
	"PERIOD_M01":     7,
	"PERIOD_M03":     8,
	"PERIOD_M05":     9,
	"PERIOD_M10":     10,
	"PERIOD_M15":     11,
	"PERIOD_M30":     12,
	"PERIOD_H01":     13,
	"PERIOD_H02":     14,
	"PERIOD_H03":     15,
	"PERIOD_H04":     16,
	"PERIOD_D01":     17,
	"PERIOD_W01":     18,
	"PERIOD_X01":     19,
}

func (x BfBarPeriod) String() string {
	return proto.EnumName(BfBarPeriod_name, int32(x))
}
func (BfBarPeriod) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// Bar行情数据类
type BfBarData struct {
	// 代码相关
	Symbol   string `protobuf:"bytes,1,opt,name=symbol" json:"symbol,omitempty"`
	Exchange string `protobuf:"bytes,2,opt,name=exchange" json:"exchange,omitempty"`
	// 周期
	Period BfBarPeriod `protobuf:"varint,3,opt,name=period,enum=bfdatafeed.BfBarPeriod" json:"period,omitempty"`
	// 成交数据
	ActionDate   string  `protobuf:"bytes,4,opt,name=actionDate" json:"actionDate,omitempty"`
	BarTime      string  `protobuf:"bytes,5,opt,name=barTime" json:"barTime,omitempty"`
	Volume       int32   `protobuf:"varint,6,opt,name=volume" json:"volume,omitempty"`
	OpenInterest float64 `protobuf:"fixed64,7,opt,name=openInterest" json:"openInterest,omitempty"`
	LastVolume   int32   `protobuf:"varint,8,opt,name=lastVolume" json:"lastVolume,omitempty"`
	// OHLC
	OpenPrice  float64 `protobuf:"fixed64,9,opt,name=openPrice" json:"openPrice,omitempty"`
	HighPrice  float64 `protobuf:"fixed64,10,opt,name=highPrice" json:"highPrice,omitempty"`
	LowPrice   float64 `protobuf:"fixed64,11,opt,name=lowPrice" json:"lowPrice,omitempty"`
	ClosePrice float64 `protobuf:"fixed64,12,opt,name=closePrice" json:"closePrice,omitempty"`
}

func (m *BfBarData) Reset()                    { *m = BfBarData{} }
func (m *BfBarData) String() string            { return proto.CompactTextString(m) }
func (*BfBarData) ProtoMessage()               {}
func (*BfBarData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type BfGetTickReq struct {
	// 代码编号相关
	Symbol   string `protobuf:"bytes,1,opt,name=symbol" json:"symbol,omitempty"`
	Exchange string `protobuf:"bytes,2,opt,name=exchange" json:"exchange,omitempty"`
	ToDate   string `protobuf:"bytes,3,opt,name=toDate" json:"toDate,omitempty"`
	ToTime   string `protobuf:"bytes,4,opt,name=toTime" json:"toTime,omitempty"`
	Count    int32  `protobuf:"varint,5,opt,name=count" json:"count,omitempty"`
}

func (m *BfGetTickReq) Reset()                    { *m = BfGetTickReq{} }
func (m *BfGetTickReq) String() string            { return proto.CompactTextString(m) }
func (*BfGetTickReq) ProtoMessage()               {}
func (*BfGetTickReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type BfGetBarReq struct {
	// 代码编号相关
	Symbol   string      `protobuf:"bytes,1,opt,name=symbol" json:"symbol,omitempty"`
	Exchange string      `protobuf:"bytes,2,opt,name=exchange" json:"exchange,omitempty"`
	Period   BfBarPeriod `protobuf:"varint,3,opt,name=period,enum=bfdatafeed.BfBarPeriod" json:"period,omitempty"`
	ToDate   string      `protobuf:"bytes,4,opt,name=toDate" json:"toDate,omitempty"`
	ToTime   string      `protobuf:"bytes,5,opt,name=toTime" json:"toTime,omitempty"`
	Count    int32       `protobuf:"varint,6,opt,name=count" json:"count,omitempty"`
}

func (m *BfGetBarReq) Reset()                    { *m = BfGetBarReq{} }
func (m *BfGetBarReq) String() string            { return proto.CompactTextString(m) }
func (*BfGetBarReq) ProtoMessage()               {}
func (*BfGetBarReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type BfDeleteTickReq struct {
	// 代码编号相关
	Symbol   string `protobuf:"bytes,1,opt,name=symbol" json:"symbol,omitempty"`
	Exchange string `protobuf:"bytes,2,opt,name=exchange" json:"exchange,omitempty"`
	ToDate   string `protobuf:"bytes,3,opt,name=toDate" json:"toDate,omitempty"`
	ToTime   string `protobuf:"bytes,4,opt,name=toTime" json:"toTime,omitempty"`
	FromDate string `protobuf:"bytes,5,opt,name=fromDate" json:"fromDate,omitempty"`
	FromTime string `protobuf:"bytes,6,opt,name=fromTime" json:"fromTime,omitempty"`
}

func (m *BfDeleteTickReq) Reset()                    { *m = BfDeleteTickReq{} }
func (m *BfDeleteTickReq) String() string            { return proto.CompactTextString(m) }
func (*BfDeleteTickReq) ProtoMessage()               {}
func (*BfDeleteTickReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type BfDeleteBarReq struct {
	// 代码编号相关
	Symbol   string      `protobuf:"bytes,1,opt,name=symbol" json:"symbol,omitempty"`
	Exchange string      `protobuf:"bytes,2,opt,name=exchange" json:"exchange,omitempty"`
	Period   BfBarPeriod `protobuf:"varint,3,opt,name=period,enum=bfdatafeed.BfBarPeriod" json:"period,omitempty"`
	ToDate   string      `protobuf:"bytes,4,opt,name=toDate" json:"toDate,omitempty"`
	ToTime   string      `protobuf:"bytes,5,opt,name=toTime" json:"toTime,omitempty"`
	FromDate string      `protobuf:"bytes,6,opt,name=fromDate" json:"fromDate,omitempty"`
	FromTime string      `protobuf:"bytes,7,opt,name=fromTime" json:"fromTime,omitempty"`
}

func (m *BfDeleteBarReq) Reset()                    { *m = BfDeleteBarReq{} }
func (m *BfDeleteBarReq) String() string            { return proto.CompactTextString(m) }
func (*BfDeleteBarReq) ProtoMessage()               {}
func (*BfDeleteBarReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type BfDeleteContractReq struct {
	// 代码编号相关
	Symbol   string `protobuf:"bytes,1,opt,name=symbol" json:"symbol,omitempty"`
	Exchange string `protobuf:"bytes,2,opt,name=exchange" json:"exchange,omitempty"`
}

func (m *BfDeleteContractReq) Reset()                    { *m = BfDeleteContractReq{} }
func (m *BfDeleteContractReq) String() string            { return proto.CompactTextString(m) }
func (*BfDeleteContractReq) ProtoMessage()               {}
func (*BfDeleteContractReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func init() {
	proto.RegisterType((*BfBarData)(nil), "bfdatafeed.BfBarData")
	proto.RegisterType((*BfGetTickReq)(nil), "bfdatafeed.BfGetTickReq")
	proto.RegisterType((*BfGetBarReq)(nil), "bfdatafeed.BfGetBarReq")
	proto.RegisterType((*BfDeleteTickReq)(nil), "bfdatafeed.BfDeleteTickReq")
	proto.RegisterType((*BfDeleteBarReq)(nil), "bfdatafeed.BfDeleteBarReq")
	proto.RegisterType((*BfDeleteContractReq)(nil), "bfdatafeed.BfDeleteContractReq")
	proto.RegisterEnum("bfdatafeed.BfBarPeriod", BfBarPeriod_name, BfBarPeriod_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion2

// Client API for BfDatafeedService service

type BfDatafeedServiceClient interface {
	// 活跃检测
	Ping(ctx context.Context, in *bfgateway.BfPingData, opts ...grpc.CallOption) (*bfgateway.BfPingData, error)
	// 保存tick
	InsertTick(ctx context.Context, in *bfgateway.BfTickData, opts ...grpc.CallOption) (*bfgateway.BfVoid, error)
	// 保存bar
	InsertBar(ctx context.Context, in *BfBarData, opts ...grpc.CallOption) (*bfgateway.BfVoid, error)
	// 保存contract
	InsertContract(ctx context.Context, in *bfgateway.BfContractData, opts ...grpc.CallOption) (*bfgateway.BfVoid, error)
	// 获取tick
	GetTick(ctx context.Context, in *BfGetTickReq, opts ...grpc.CallOption) (BfDatafeedService_GetTickClient, error)
	// 获取bar
	GetBar(ctx context.Context, in *BfGetBarReq, opts ...grpc.CallOption) (BfDatafeedService_GetBarClient, error)
	// 获取contract, 支持* *获取全部订阅合约
	GetContract(ctx context.Context, in *bfgateway.BfGetContractReq, opts ...grpc.CallOption) (BfDatafeedService_GetContractClient, error)
	// 删除tick
	DeleteTick(ctx context.Context, in *BfDeleteTickReq, opts ...grpc.CallOption) (*bfgateway.BfVoid, error)
	// 删除bar
	DeleteBar(ctx context.Context, in *BfDeleteBarReq, opts ...grpc.CallOption) (*bfgateway.BfVoid, error)
	// 删除contract，支持* *删除全部合约
	DeleteContract(ctx context.Context, in *BfDeleteContractReq, opts ...grpc.CallOption) (*bfgateway.BfVoid, error)
	// 重置数据库
	CleanAll(ctx context.Context, in *bfgateway.BfVoid, opts ...grpc.CallOption) (*bfgateway.BfVoid, error)
}

type bfDatafeedServiceClient struct {
	cc *grpc.ClientConn
}

func NewBfDatafeedServiceClient(cc *grpc.ClientConn) BfDatafeedServiceClient {
	return &bfDatafeedServiceClient{cc}
}

func (c *bfDatafeedServiceClient) Ping(ctx context.Context, in *bfgateway.BfPingData, opts ...grpc.CallOption) (*bfgateway.BfPingData, error) {
	out := new(bfgateway.BfPingData)
	err := grpc.Invoke(ctx, "/bfdatafeed.BfDatafeedService/Ping", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bfDatafeedServiceClient) InsertTick(ctx context.Context, in *bfgateway.BfTickData, opts ...grpc.CallOption) (*bfgateway.BfVoid, error) {
	out := new(bfgateway.BfVoid)
	err := grpc.Invoke(ctx, "/bfdatafeed.BfDatafeedService/InsertTick", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bfDatafeedServiceClient) InsertBar(ctx context.Context, in *BfBarData, opts ...grpc.CallOption) (*bfgateway.BfVoid, error) {
	out := new(bfgateway.BfVoid)
	err := grpc.Invoke(ctx, "/bfdatafeed.BfDatafeedService/InsertBar", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bfDatafeedServiceClient) InsertContract(ctx context.Context, in *bfgateway.BfContractData, opts ...grpc.CallOption) (*bfgateway.BfVoid, error) {
	out := new(bfgateway.BfVoid)
	err := grpc.Invoke(ctx, "/bfdatafeed.BfDatafeedService/InsertContract", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bfDatafeedServiceClient) GetTick(ctx context.Context, in *BfGetTickReq, opts ...grpc.CallOption) (BfDatafeedService_GetTickClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_BfDatafeedService_serviceDesc.Streams[0], c.cc, "/bfdatafeed.BfDatafeedService/GetTick", opts...)
	if err != nil {
		return nil, err
	}
	x := &bfDatafeedServiceGetTickClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type BfDatafeedService_GetTickClient interface {
	Recv() (*bfgateway.BfTickData, error)
	grpc.ClientStream
}

type bfDatafeedServiceGetTickClient struct {
	grpc.ClientStream
}

func (x *bfDatafeedServiceGetTickClient) Recv() (*bfgateway.BfTickData, error) {
	m := new(bfgateway.BfTickData)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *bfDatafeedServiceClient) GetBar(ctx context.Context, in *BfGetBarReq, opts ...grpc.CallOption) (BfDatafeedService_GetBarClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_BfDatafeedService_serviceDesc.Streams[1], c.cc, "/bfdatafeed.BfDatafeedService/GetBar", opts...)
	if err != nil {
		return nil, err
	}
	x := &bfDatafeedServiceGetBarClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type BfDatafeedService_GetBarClient interface {
	Recv() (*BfBarData, error)
	grpc.ClientStream
}

type bfDatafeedServiceGetBarClient struct {
	grpc.ClientStream
}

func (x *bfDatafeedServiceGetBarClient) Recv() (*BfBarData, error) {
	m := new(BfBarData)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *bfDatafeedServiceClient) GetContract(ctx context.Context, in *bfgateway.BfGetContractReq, opts ...grpc.CallOption) (BfDatafeedService_GetContractClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_BfDatafeedService_serviceDesc.Streams[2], c.cc, "/bfdatafeed.BfDatafeedService/GetContract", opts...)
	if err != nil {
		return nil, err
	}
	x := &bfDatafeedServiceGetContractClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type BfDatafeedService_GetContractClient interface {
	Recv() (*bfgateway.BfContractData, error)
	grpc.ClientStream
}

type bfDatafeedServiceGetContractClient struct {
	grpc.ClientStream
}

func (x *bfDatafeedServiceGetContractClient) Recv() (*bfgateway.BfContractData, error) {
	m := new(bfgateway.BfContractData)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *bfDatafeedServiceClient) DeleteTick(ctx context.Context, in *BfDeleteTickReq, opts ...grpc.CallOption) (*bfgateway.BfVoid, error) {
	out := new(bfgateway.BfVoid)
	err := grpc.Invoke(ctx, "/bfdatafeed.BfDatafeedService/DeleteTick", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bfDatafeedServiceClient) DeleteBar(ctx context.Context, in *BfDeleteBarReq, opts ...grpc.CallOption) (*bfgateway.BfVoid, error) {
	out := new(bfgateway.BfVoid)
	err := grpc.Invoke(ctx, "/bfdatafeed.BfDatafeedService/DeleteBar", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bfDatafeedServiceClient) DeleteContract(ctx context.Context, in *BfDeleteContractReq, opts ...grpc.CallOption) (*bfgateway.BfVoid, error) {
	out := new(bfgateway.BfVoid)
	err := grpc.Invoke(ctx, "/bfdatafeed.BfDatafeedService/DeleteContract", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bfDatafeedServiceClient) CleanAll(ctx context.Context, in *bfgateway.BfVoid, opts ...grpc.CallOption) (*bfgateway.BfVoid, error) {
	out := new(bfgateway.BfVoid)
	err := grpc.Invoke(ctx, "/bfdatafeed.BfDatafeedService/CleanAll", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for BfDatafeedService service

type BfDatafeedServiceServer interface {
	// 活跃检测
	Ping(context.Context, *bfgateway.BfPingData) (*bfgateway.BfPingData, error)
	// 保存tick
	InsertTick(context.Context, *bfgateway.BfTickData) (*bfgateway.BfVoid, error)
	// 保存bar
	InsertBar(context.Context, *BfBarData) (*bfgateway.BfVoid, error)
	// 保存contract
	InsertContract(context.Context, *bfgateway.BfContractData) (*bfgateway.BfVoid, error)
	// 获取tick
	GetTick(*BfGetTickReq, BfDatafeedService_GetTickServer) error
	// 获取bar
	GetBar(*BfGetBarReq, BfDatafeedService_GetBarServer) error
	// 获取contract, 支持* *获取全部订阅合约
	GetContract(*bfgateway.BfGetContractReq, BfDatafeedService_GetContractServer) error
	// 删除tick
	DeleteTick(context.Context, *BfDeleteTickReq) (*bfgateway.BfVoid, error)
	// 删除bar
	DeleteBar(context.Context, *BfDeleteBarReq) (*bfgateway.BfVoid, error)
	// 删除contract，支持* *删除全部合约
	DeleteContract(context.Context, *BfDeleteContractReq) (*bfgateway.BfVoid, error)
	// 重置数据库
	CleanAll(context.Context, *bfgateway.BfVoid) (*bfgateway.BfVoid, error)
}

func RegisterBfDatafeedServiceServer(s *grpc.Server, srv BfDatafeedServiceServer) {
	s.RegisterService(&_BfDatafeedService_serviceDesc, srv)
}

func _BfDatafeedService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(bfgateway.BfPingData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BfDatafeedServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bfdatafeed.BfDatafeedService/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BfDatafeedServiceServer).Ping(ctx, req.(*bfgateway.BfPingData))
	}
	return interceptor(ctx, in, info, handler)
}

func _BfDatafeedService_InsertTick_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(bfgateway.BfTickData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BfDatafeedServiceServer).InsertTick(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bfdatafeed.BfDatafeedService/InsertTick",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BfDatafeedServiceServer).InsertTick(ctx, req.(*bfgateway.BfTickData))
	}
	return interceptor(ctx, in, info, handler)
}

func _BfDatafeedService_InsertBar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BfBarData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BfDatafeedServiceServer).InsertBar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bfdatafeed.BfDatafeedService/InsertBar",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BfDatafeedServiceServer).InsertBar(ctx, req.(*BfBarData))
	}
	return interceptor(ctx, in, info, handler)
}

func _BfDatafeedService_InsertContract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(bfgateway.BfContractData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BfDatafeedServiceServer).InsertContract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bfdatafeed.BfDatafeedService/InsertContract",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BfDatafeedServiceServer).InsertContract(ctx, req.(*bfgateway.BfContractData))
	}
	return interceptor(ctx, in, info, handler)
}

func _BfDatafeedService_GetTick_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BfGetTickReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BfDatafeedServiceServer).GetTick(m, &bfDatafeedServiceGetTickServer{stream})
}

type BfDatafeedService_GetTickServer interface {
	Send(*bfgateway.BfTickData) error
	grpc.ServerStream
}

type bfDatafeedServiceGetTickServer struct {
	grpc.ServerStream
}

func (x *bfDatafeedServiceGetTickServer) Send(m *bfgateway.BfTickData) error {
	return x.ServerStream.SendMsg(m)
}

func _BfDatafeedService_GetBar_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BfGetBarReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BfDatafeedServiceServer).GetBar(m, &bfDatafeedServiceGetBarServer{stream})
}

type BfDatafeedService_GetBarServer interface {
	Send(*BfBarData) error
	grpc.ServerStream
}

type bfDatafeedServiceGetBarServer struct {
	grpc.ServerStream
}

func (x *bfDatafeedServiceGetBarServer) Send(m *BfBarData) error {
	return x.ServerStream.SendMsg(m)
}

func _BfDatafeedService_GetContract_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(bfgateway.BfGetContractReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BfDatafeedServiceServer).GetContract(m, &bfDatafeedServiceGetContractServer{stream})
}

type BfDatafeedService_GetContractServer interface {
	Send(*bfgateway.BfContractData) error
	grpc.ServerStream
}

type bfDatafeedServiceGetContractServer struct {
	grpc.ServerStream
}

func (x *bfDatafeedServiceGetContractServer) Send(m *bfgateway.BfContractData) error {
	return x.ServerStream.SendMsg(m)
}

func _BfDatafeedService_DeleteTick_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BfDeleteTickReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BfDatafeedServiceServer).DeleteTick(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bfdatafeed.BfDatafeedService/DeleteTick",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BfDatafeedServiceServer).DeleteTick(ctx, req.(*BfDeleteTickReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BfDatafeedService_DeleteBar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BfDeleteBarReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BfDatafeedServiceServer).DeleteBar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bfdatafeed.BfDatafeedService/DeleteBar",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BfDatafeedServiceServer).DeleteBar(ctx, req.(*BfDeleteBarReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BfDatafeedService_DeleteContract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BfDeleteContractReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BfDatafeedServiceServer).DeleteContract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bfdatafeed.BfDatafeedService/DeleteContract",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BfDatafeedServiceServer).DeleteContract(ctx, req.(*BfDeleteContractReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BfDatafeedService_CleanAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(bfgateway.BfVoid)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BfDatafeedServiceServer).CleanAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bfdatafeed.BfDatafeedService/CleanAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BfDatafeedServiceServer).CleanAll(ctx, req.(*bfgateway.BfVoid))
	}
	return interceptor(ctx, in, info, handler)
}

var _BfDatafeedService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bfdatafeed.BfDatafeedService",
	HandlerType: (*BfDatafeedServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _BfDatafeedService_Ping_Handler,
		},
		{
			MethodName: "InsertTick",
			Handler:    _BfDatafeedService_InsertTick_Handler,
		},
		{
			MethodName: "InsertBar",
			Handler:    _BfDatafeedService_InsertBar_Handler,
		},
		{
			MethodName: "InsertContract",
			Handler:    _BfDatafeedService_InsertContract_Handler,
		},
		{
			MethodName: "DeleteTick",
			Handler:    _BfDatafeedService_DeleteTick_Handler,
		},
		{
			MethodName: "DeleteBar",
			Handler:    _BfDatafeedService_DeleteBar_Handler,
		},
		{
			MethodName: "DeleteContract",
			Handler:    _BfDatafeedService_DeleteContract_Handler,
		},
		{
			MethodName: "CleanAll",
			Handler:    _BfDatafeedService_CleanAll_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetTick",
			Handler:       _BfDatafeedService_GetTick_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetBar",
			Handler:       _BfDatafeedService_GetBar_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetContract",
			Handler:       _BfDatafeedService_GetContract_Handler,
			ServerStreams: true,
		},
	},
}

var fileDescriptor0 = []byte{
	// 763 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xcc, 0x56, 0xdf, 0x72, 0xd2, 0x4e,
	0x14, 0x6e, 0x28, 0x04, 0x38, 0xf0, 0xa3, 0xdb, 0xed, 0x4f, 0x1b, 0xd1, 0x51, 0x87, 0xab, 0x4e,
	0x2f, 0x80, 0x82, 0xa8, 0x17, 0x9d, 0x8e, 0x52, 0xfc, 0xc3, 0x38, 0xb6, 0x0c, 0xad, 0xad, 0xe3,
	0x8d, 0x13, 0x60, 0x03, 0x19, 0x43, 0x16, 0x43, 0x68, 0xed, 0x1b, 0xf8, 0x32, 0xde, 0x7b, 0xef,
	0x13, 0xf8, 0x00, 0xbe, 0x8a, 0xe3, 0x66, 0x17, 0x92, 0xdd, 0x36, 0x38, 0x63, 0x2f, 0x1c, 0x2f,
	0xbf, 0xef, 0x3b, 0xdf, 0xd9, 0x73, 0xce, 0x6e, 0x0e, 0x00, 0xea, 0x59, 0x03, 0xd3, 0x37, 0x2d,
	0x42, 0x06, 0xe5, 0x89, 0x47, 0x7d, 0x8a, 0x21, 0x62, 0x8a, 0x6b, 0x3d, 0x6b, 0x68, 0xfa, 0xe4,
	0xdc, 0xbc, 0x10, 0x62, 0xe9, 0x67, 0x02, 0xb2, 0x4d, 0xab, 0x69, 0x7a, 0x2d, 0x16, 0x82, 0x6f,
	0x82, 0x3e, 0xbd, 0x18, 0xf7, 0xa8, 0x63, 0x68, 0xf7, 0xb5, 0xad, 0x6c, 0x77, 0x8e, 0x70, 0x11,
	0x32, 0xe4, 0x53, 0x7f, 0x64, 0xba, 0x43, 0x62, 0x24, 0xb8, 0x12, 0x62, 0x5c, 0x01, 0x7d, 0x42,
	0x3c, 0x9b, 0x0e, 0x8c, 0x55, 0xa6, 0x14, 0x6a, 0x9b, 0x65, 0xa9, 0x02, 0x9e, 0xba, 0xc3, 0xe5,
	0xee, 0x3c, 0x0c, 0xdf, 0x05, 0x30, 0xfb, 0xbe, 0x4d, 0x5d, 0x76, 0x24, 0x31, 0x92, 0x3c, 0x9d,
	0xc4, 0x60, 0x03, 0xd2, 0x3d, 0xd3, 0x3b, 0xb6, 0xc7, 0xc4, 0x48, 0x71, 0x71, 0x01, 0x83, 0xf2,
	0xce, 0xa8, 0x33, 0x63, 0x82, 0xce, 0x84, 0x54, 0x77, 0x8e, 0x70, 0x09, 0xf2, 0x74, 0x42, 0xdc,
	0xb6, 0xeb, 0x13, 0x8f, 0x4c, 0x7d, 0x23, 0xcd, 0x54, 0xad, 0xab, 0x70, 0xc1, 0xa9, 0x8e, 0x39,
	0xf5, 0x4f, 0x84, 0x3f, 0xc3, 0xfd, 0x12, 0x83, 0xef, 0x40, 0x36, 0x88, 0xef, 0x78, 0x76, 0x9f,
	0x18, 0x59, 0x9e, 0x20, 0x22, 0x02, 0x75, 0x64, 0x0f, 0x47, 0x42, 0x05, 0xa1, 0x86, 0x44, 0x30,
	0x1e, 0x87, 0x9e, 0x0b, 0x31, 0xc7, 0xc5, 0x10, 0x07, 0xe7, 0xf6, 0x1d, 0x3a, 0x25, 0x42, 0xcd,
	0x73, 0x55, 0x62, 0x4a, 0x9f, 0x35, 0xc8, 0x37, 0xad, 0x17, 0xc4, 0x3f, 0xb6, 0xfb, 0x1f, 0xba,
	0xe4, 0xe3, 0xb5, 0xee, 0x80, 0x79, 0x7c, 0xca, 0xc7, 0xb9, 0x2a, 0x3c, 0x02, 0x09, 0x9e, 0x4f,
	0x32, 0xb9, 0xe0, 0xf9, 0x20, 0xff, 0x87, 0x54, 0x9f, 0xce, 0x5c, 0x9f, 0x0f, 0x38, 0xd5, 0x15,
	0xa0, 0xf4, 0x55, 0x83, 0x1c, 0x2f, 0x85, 0xdd, 0xd9, 0x75, 0x2b, 0xf9, 0xe3, 0xd7, 0x10, 0x95,
	0x9e, 0x5c, 0x52, 0x7a, 0x2a, 0xbe, 0x74, 0x5d, 0x2e, 0xfd, 0x8b, 0x06, 0x6b, 0x4d, 0xab, 0x45,
	0x1c, 0xe2, 0x93, 0xbf, 0x39, 0x48, 0x96, 0xcb, 0xf2, 0xe8, 0x98, 0x3b, 0x44, 0x9d, 0x21, 0x5e,
	0x68, 0xdc, 0xa5, 0x47, 0x5a, 0x80, 0x4b, 0x3f, 0x34, 0x28, 0x2c, 0xea, 0xfd, 0x97, 0xa7, 0x2d,
	0xf7, 0xa7, 0xff, 0xa6, 0xbf, 0xf4, 0xa5, 0xfe, 0xda, 0xb0, 0xb1, 0x68, 0x6f, 0x9f, 0xba, 0xbe,
	0xc7, 0x3e, 0xef, 0x6b, 0xf6, 0xb8, 0xfd, 0x3d, 0x11, 0xbc, 0xca, 0xb0, 0x15, 0x8c, 0xa1, 0xd0,
	0x79, 0xd6, 0x6d, 0x1f, 0xb6, 0xde, 0xbf, 0x39, 0x78, 0x75, 0x70, 0x78, 0x7a, 0x80, 0x56, 0x70,
	0x01, 0x60, 0xce, 0x1d, 0x55, 0x77, 0x90, 0xa6, 0xe0, 0x3a, 0x4a, 0x28, 0xb8, 0x81, 0x56, 0x65,
	0xbc, 0x53, 0x45, 0x49, 0x05, 0x37, 0x50, 0x4a, 0xc6, 0xf5, 0x2a, 0xd2, 0x25, 0xfc, 0x9a, 0xe5,
	0x4f, 0x2b, 0xb8, 0x8e, 0x32, 0x0a, 0x6e, 0xa0, 0xac, 0x8c, 0x59, 0x7e, 0x50, 0x70, 0x03, 0xe5,
	0x64, 0xcc, 0xf2, 0xe7, 0x25, 0xfc, 0x92, 0xe5, 0xff, 0x4f, 0xc1, 0x35, 0x54, 0x50, 0x70, 0x1d,
	0xad, 0x29, 0xf8, 0x01, 0x42, 0x12, 0x6e, 0x31, 0xff, 0xba, 0x84, 0x4f, 0x19, 0xc6, 0x12, 0x7e,
	0xcb, 0xf0, 0x46, 0xed, 0x5b, 0x0a, 0xd6, 0xd9, 0xfd, 0xcc, 0x5f, 0xca, 0x11, 0xf1, 0xce, 0x82,
	0x55, 0xf5, 0x10, 0x92, 0x1d, 0xdb, 0x1d, 0xe2, 0x1b, 0xe5, 0xe8, 0x57, 0xa2, 0x69, 0x05, 0x54,
	0x10, 0x59, 0x8c, 0xa7, 0x4b, 0x2b, 0xf8, 0x31, 0x40, 0xdb, 0x9d, 0x12, 0x8f, 0xaf, 0xb0, 0x4b,
	0xee, 0x80, 0xe2, 0xee, 0x75, 0x85, 0x3e, 0xa1, 0xf6, 0x80, 0x39, 0x1f, 0x41, 0x56, 0x38, 0xd9,
	0xf5, 0x72, 0xa3, 0xfa, 0x78, 0x97, 0x1b, 0x9f, 0x40, 0x41, 0x18, 0x17, 0xaf, 0x0b, 0xdf, 0x52,
	0xc2, 0x16, 0xf4, 0xf2, 0x0c, 0x7b, 0x90, 0x9e, 0x2f, 0x5d, 0x6c, 0xa8, 0x07, 0x47, 0xbb, 0xb8,
	0x18, 0xdf, 0x4b, 0x69, 0xa5, 0xaa, 0xe1, 0x5d, 0xd0, 0xc5, 0xa6, 0xc4, 0x9b, 0x57, 0xec, 0xe2,
	0x8b, 0x2e, 0xc6, 0x37, 0xc4, 0xdd, 0x6d, 0xc8, 0xb1, 0xb8, 0xb0, 0xf8, 0xdb, 0xca, 0x39, 0x92,
	0x12, 0xa4, 0x59, 0xde, 0x19, 0x4f, 0xb5, 0x07, 0x10, 0xed, 0x3d, 0x9e, 0x49, 0x3a, 0x53, 0xd9,
	0x88, 0xf1, 0x83, 0xd8, 0x85, 0x6c, 0xb8, 0x87, 0x70, 0x31, 0xce, 0x3e, 0x6f, 0x27, 0xd6, 0xfd,
	0x1c, 0x0a, 0xea, 0x67, 0x8e, 0xef, 0xc5, 0xa5, 0x90, 0xfb, 0x89, 0xcd, 0x53, 0x83, 0xcc, 0xbe,
	0x43, 0x4c, 0xf7, 0xa9, 0xe3, 0xe0, 0xab, 0x01, 0xb1, 0x9e, 0xe6, 0xf6, 0xbb, 0xad, 0xa1, 0xed,
	0x8f, 0x66, 0xbd, 0x72, 0x9f, 0x8e, 0x2b, 0xd3, 0x99, 0x7b, 0xce, 0x16, 0xc6, 0x98, 0x54, 0x58,
	0x28, 0xad, 0x98, 0x13, 0xbb, 0x12, 0x15, 0xd2, 0xd3, 0xf9, 0xdf, 0x9d, 0xfa, 0xaf, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xc9, 0x61, 0x82, 0x8c, 0x1f, 0x09, 0x00, 0x00,
}
